version: '3.0' # specify docker-compose version

services:
 angular: #frontend server (angular)
  build: frontend 
  ports:
  - "4200:4200" 

 express: #backend server (express - nodejs)
  build: backend 
  ports:
  - "3000:3000" 
  links:
  - database # link this service to the database service

 database: #db server (mongodb)
  image: mongo 
  ports:
  - "27017:27017" 
